-- MySQL Script generated by MySQL Workbench
-- Thu May 11 15:42:58 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_autoescola
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_autoescola
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_autoescola` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `db_autoescola` ;

-- -----------------------------------------------------
-- Table `db_autoescola`.`autoescola`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_autoescola`.`autoescola` (
  `codigoatendimento` INT NOT NULL,
  `datainicio` DATE NULL DEFAULT NULL,
  `datafinalmaxima` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`codigoatendimento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_autoescola`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS dados_formulario (
  id INT NOT NULL AUTO_INCREMENT,
  nome_funcionario VARCHAR(100),
  cpf_cliente VARCHAR(14),
  observacoes TEXT,
  data DATE,
  PRIMARY KEY (id)
);



-- -----------------------------------------------------
-- Table `db_autoescola`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_autoescola`.`cliente` (
  `idcliente` INT NOT NULL,
  `nomecliente` VARCHAR(45) NULL,
  `idadecliente` INT NULL,
  `cpfcliente` INT NULL,
  `nascimentocliente` DATE NULL,
  `emailcliente` VARCHAR(45) NULL,
  `rgcliente` INT NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
