-- MySQL Script generated by MySQL Workbench
-- Mon Apr  3 16:37:38 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_autoescola
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_autoescola
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_autoescola` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `db_autoescola` ;

-- -----------------------------------------------------
-- Table `db_autoescola`.`autoescola`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_autoescola`.`autoescola` (
  `codigoatendimento` INT NOT NULL,
  `datainicio` DATE NULL,
  `datafinalmaxima` DATE NULL,
  PRIMARY KEY (`codigoatendimento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_autoescola`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_autoescola`.`funcionario` (
  `idfuncionario` INT NOT NULL,
  `nomefuncionario` VARCHAR(45) NULL,
  `cpffuncionario` INT NULL,
  `data` DATE NULL,
  PRIMARY KEY (`idfuncionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_autoescola`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_autoescola`.`cliente` (
  `idcliente` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `cpf` INT NULL,
  `rg` INT NULL,
  `datanascimento` DATE NULL,
  `email` VARCHAR(45) NULL,
  `tel/cel` INT NULL,
  `categoria` VARCHAR(3) NULL,
  `preco` DECIMAL(11,2) NULL,
  `` VARCHAR(45) NULL,
  `autoescola_codigoatendimento` INT NOT NULL,
  `funcionario_idfuncionario` INT NOT NULL,
  PRIMARY KEY (`idcliente`, `autoescola_codigoatendimento`, `funcionario_idfuncionario`),
  INDEX `fk_cliente_autoescola_idx` (`autoescola_codigoatendimento` ASC) VISIBLE,
  INDEX `fk_cliente_funcionario1_idx` (`funcionario_idfuncionario` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_autoescola`
    FOREIGN KEY (`autoescola_codigoatendimento`)
    REFERENCES `db_autoescola`.`autoescola` (`codigoatendimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_funcionario1`
    FOREIGN KEY (`funcionario_idfuncionario`)
    REFERENCES `db_autoescola`.`funcionario` (`idfuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
